all:
	$(MAKE) -C lib all
	$(MAKE) -C bt_ica all
	$(MAKE) -C rt_ica all
	$(MAKE) -C mk_nbf all

rebuild:
	$(MAKE) -C lib rebuild
	$(MAKE) -C bt_ica rebuild
	$(MAKE) -C rt_ica rebuild
	$(MAKE) -C mk_nbf rebuild

clean:
	$(MAKE) -C lib clean
	$(MAKE) -C bt_ica clean
	$(MAKE) -C rt_ica clean
	$(MAKE) -C mk_nbf clean
